version: '3.1'

services:

  database:
    platform: windows/x86_64
    image: mysql:8.0
    restart: always
    ports:
      # <Port exposed> : < MySQL Port running inside container>
      - '3306:3306'

    environment:
      MYSQL_DATABASE: 'capstonedb'
      # So you don't have to use root, but you can if you like
      # You can use whatever password you like
      MYSQL_PASSWORD: 'password'
      # Password for root access
      MYSQL_ROOT_PASSWORD: 'password'